### ISSUE TITLE
Mocha unit test failing at creating a canvas

### ISSUE THREAD

**Issue by Chaoste** [paperjs/paper.js#1172]
I'm working on a redux project where we're using paper.js for some drawing features. We're testing our code in docker containers with mocha (unit tests) and nightwatch (integration tests, incl. selenium server). For installing dependencies we're using npm (`npm install paper`).

All tests are working on my machine. If I'm pushing the code to my repository (BitBucket) the Continuous Integration tool (Bamboo) starts building the docker containers and runs the tests. Then i'll get the following error:

Console output (Bamboo log):

    Error: Canvas [object HTMLCanvasElement] is unable toprovide a 2D context.
        at Object.CanvasProvider.getCanvas (/home/nexboard/Nexboard/node_modules/paper/dist/paper-full.js:12919:10)
        at Object.CanvasProvider.getContext (/home/nexboard/Nexboard/node_modules/paper/dist/paper-full.js:12934:21)
        at new <anonymous> (/home/nexboard/Nexboard/node_modules/paper/dist/paper-full.js:13133:27)
        at Object.<anonymous> (/home/nexboard/Nexboard/node_modules/paper/dist/paper-full.js:12947:17)
        at Object.<anonymous> (/home/nexboard/Nexboard/node_modules/paper/dist/paper-full.js:14623:3)
        at Module._compile (module.js:541:32)
        at Module.replacementCompile (/home/nexboard/node_modules/nyc/node_modules/append-transform/index.js:63:13)
        at module.exports (/home/nexboard/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
        at /home/nexboard/node_modules/nyc/node_modules/append-transform/index.js:67:4
        at require.extensions.(anonymous function) (/home/nexboard/node_modules/babel-register/lib/node.js:154:7)
        at /home/nexboard/node_modules/nyc/node_modules/append-transform/index.js:67:4
        at require.extensions.(anonymous function) (/home/nexboard/Nexboard/node_modules/babel-register/lib/node.js:154:7)
        at Object.<anonymous> (/home/nexboard/node_modules/nyc/node_modules/append-transform/index.js:67:4)
        at Module.load (module.js:458:32)
        at tryModuleLoad (module.js:417:12)
        at Function.Module._load (module.js:409:3)
        at Module.require (module.js:468:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/home/nexboard/Nexboard/src/js/whiteboard/canvas.jsx:1:13)
        at ...

Main.jsx:

    import React from 'react';
    import Toolbar from '../userinterface/Toolbar/Toolbar.jsx';
    import Canvas from '../whiteboard/canvas.jsx';

    export function Main() {
      return (
        <main className="main">
          <div id="content">
            <Toolbar />
          </div>
          <div id="background"></div>
          <Canvas />
        </main>
      );
    }

    export default Main;

canvas.jsx

    import React from 'react';
    import paper from 'paper';

    var Canvas = React.createClass({

      componentDidMount: () => {
        console.log("Canvas did mount")
        console.log(paper)

        paper.setup('whiteboard');
        var path = new paper.Path();
    		path.strokeColor = 'black';
        var start = new paper.Point(100, 100);
    		path.moveTo(start);
    		path.lineTo(start.add([ 200, -50 ]));
    		paper.view.draw();

      },

      render: () => {
        return (
          <canvas id="whiteboard">
          </canvas>
        );
      }
    })

    export default Canvas

When mocha runs my tests and creates a main object, it fails requiring paper.js. I don't think it's because of my docker compose configuration so I'm leaving that one out. The code which is failing in paper.js are the following lines:

	if (this.canvases.length) {
		canvas = this.canvases.pop();
	} else {
		// This get's called (at the first time)
		canvas = document.createElement('canvas');
		clear = false;
	}
	var ctx = canvas.getContext('2d');
	if (!ctx) {
		throw new Error('Canvas ' + canvas +
				' is unable toprovide a 2D context.');
	}

The problem could be that you need a DOM to create a canvas context but I'm not sure how this stuff is working - especially in a testing environment. What did you do to make your unit tests be successfully?

**Comment by lehni** [comment]
Why was this closed?
