### ISSUE TITLE
How do I configure this for Travis?

### ISSUE THREAD

**Issue by ben-eb** [paperjs/paper.js#1188]
Hello,

Thanks a lot for this module! It works really well, except I've been struggling to get it running on Linux builds for Travis CI. My [OS X builds](https://travis-ci.org/ben-eb/postcss-resemble-image/jobs/170410195) work completely fine, but when trying to [install on Linux](https://travis-ci.org/ben-eb/postcss-resemble-image/jobs/170410190) I get this error:

```
5.83s$ npm test
> postcss-resemble-image@0.0.0 pretest /home/travis/build/ben-eb/postcss-resemble-image
> eslint src
> postcss-resemble-image@0.0.0 test /home/travis/build/ben-eb/postcss-resemble-image
> cross-env BABEL_ENV=test BABEL_DISABLE_CACHE=1 nyc --check-coverage --lines 100 ava
module.js:471
    throw err;
    ^
Error: Cannot find module 'canvas'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/travis/build/ben-eb/postcss-resemble-image/node_modules/paper/dist/node/canvas.js:13:14)
    at Module._compile (module.js:570:32)
```

I thought it might have been the `canvas` dependency that might have needed installing separately, so I installed that on Linux but I got this error instead: https://travis-ci.org/ben-eb/postcss-resemble-image/jobs/170414190

Would really appreciate any advice!

**Comment by ben-eb** [comment]
I've got it to work by specifying the g++ version as you have in your Travis config. Now I have to deal with the joys of different colours being output on different OS versions! Sorry for the noise. 😄

https://travis-ci.org/ben-eb/postcss-resemble-image/jobs/170424143
