### ISSUE TITLE
v0.10.3 Uncaught TypeError: Cannot read property '_shiftless' of null

### ISSUE THREAD

**Issue by hapticdata** [paperjs/paper.js#1271]
I switched from v0.10.2 to v0.10.3 today and now I always get this error on every page load.

>Uncaught TypeError: Cannot read property '_shiftless' of null
    at Group._hitTest (http://localhost:9966/index.js:23329:24)
    at Layer.hitTestChildren (http://localhost:9966/index.js:23294:43)
    at Layer._hitTestChildren (http://localhost:9966/index.js:24193:30)
    at Layer._hitTest (http://localhost:9966/index.js:23380:15)
    at Project.hitTestChildren (http://localhost:9966/index.js:23294:43)
    at Project.hitTest (http://localhost:9966/index.js:23276:15)
    at CanvasView._handleMouseEvent (http://localhost:9966/index.js:32296:47)
    at handleMouseMove (http://localhost:9966/index.js:32100:8)
    at HTMLDocument.docEvents.(anonymous function) (http://localhost:9966/index.js:32170:4)

It appears that `Matrix#invert()` is returning null causing [the chained call to `_shiftless()` to fail](https://github.com/paperjs/paper.js/blob/develop/src/item/Item.js#L1904)

**Comment by lehni** [comment]
Could you provide a test case that allow me to reproduce this problem?

**Comment by lehni** [comment]
You're probably scaling an item to 0, resulting in the matrix not being revertible? That does indeed produce this error:

[Example Sketch](http://sketch.paperjs.org/#S/NY5BDoIwEEWvMukGSAip2xJX3kDYURa1jFIpU9I2mki4u0XiLH7y3+K/WRmpGZlgzYRRj6xk2g17fykPJuIMZyB8QzOqBasr6qjoYTFfJUG6xRmKAjpeAu/LgwXzwYROPMEUf3w31l6cdV5A5nHIJG1FLUnSbqmCVmmVH2Tx7plM1WhiiyHmx3xRp+9uHtX0swYmun77Ag==)
