### ISSUE TITLE
syntax errors in paper.js source code?

### ISSUE THREAD

**Issue by lpy1994** [paperjs/paper.js#1453]
unable to load in paper-full.js
inspect the file in chrome and these appears

paper-full.js:14947
Uncaught SyntaxError: Unexpected token (3:11)
    at raise (paper-full.js:14947)
    at unexpected (paper-full.js:15719)
    at semicolon (paper-full.js:15710)
    at parseStatement (paper-full.js:15939)
    at parseTopLevel (paper-full.js:15740)
    at Object.exports.parse (paper-full.js:14855)
    at parse (paper-full.js:16321)
    at compile (paper-full.js:16556)
    at execute (paper-full.js:16587)
    at HTMLCollection.loadScript (paper-full.js:16671)

**Comment by lehni** [comment]
Are you using PaperScript? I don't think this error is caused by paper.js itself, but by a script you're trying to load through it. Could you link to a code sample that causes this error? In isolation and without a way to reproduce the problem, there is nothing I can do about this.

**Comment by lpy1994** [comment]
```<!DOCTYPE html>
<html>

<head>

    <script type="text/javascript" src="paper-full.js"></script>
    <script type="text/paperscript" canvas="myCanvas">
        // Create a Paper.js Path to draw a line into it:
        var path = new Path();
        // Give the stroke a color
        path.strokeColor = 'black';
        var start = new Point(100, 100);
        // Move to start and draw a line from there
        path.moveTo(start);
        // Note the plus operator on Point objects.
        // PaperScript does that for us, and much more!
        path.lineTo(start + [100, -50]);
    </script>

</head>

<body>
    <canvas id="myCanvas" resize></canvas>
</body>

</html>```
just the Script Configuration as I was trying to do it on my computer.
maybe its about the paperScript.

**Comment by lehni** [comment]
Works for me:
```html
<head>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/paper.js/0.11.5/paper-full.js"></script>
    <script type="text/paperscript" canvas="myCanvas">
        // Create a Paper.js Path to draw a line into it:
        var path = new Path();
        // Give the stroke a color
        path.strokeColor = 'black';
        var start = new Point(100, 100);
        // Move to start and draw a line from there
        path.moveTo(start);
        // Note the plus operator on Point objects.
        // PaperScript does that for us, and much more!
        path.lineTo(start + [100, -50]);
    </script>
</head>
<body>
    <canvas id="myCanvas" resize></canvas>
</body>
</html>
```

**Comment by lpy1994** [comment]
wont be able to loaded it from cloudflare either to me. text editor: VS code. so im gonna assume that there is a problem with my text editor.
but thx anyways

**Comment by lehni** [comment]
You're not opening it in a web browser to test?

**Comment by zaihaijiao** [comment]
maybe you can try path.add(new point()) test

**Comment by 160303105370** [comment]
> ```
> <!DOCTYPE html>
> <html>
> 
> <head>
> 
>     <script type="text/javascript" src="paper-full.js"></script>
>     <script type="text/paperscript" canvas="myCanvas">
>         // Create a Paper.js Path to draw a line into it:
>         var path = new Path();
>         // Give the stroke a color
>         path.strokeColor = 'black';
>         var start = new Point(100, 100);
>         // Move to start and draw a line from there
>         path.moveTo(start);
>         // Note the plus operator on Point objects.
>         // PaperScript does that for us, and much more!
>         path.lineTo(start + [100, -50]);
>     </script>
> 
> </head>
> 
> <body>
>     <canvas id="myCanvas" resize></canvas>
> </body>
> 
> </html>
> ```
> 
> just the Script Configuration as I was trying to do it on my computer. i donwload the paper-full.js in my file and load it correctly
> maybe its about the paperScript.

**Comment by 160303105370** [comment]
I am facing the same problem even if I use it from CDN I don't think it's because of the browser. So, if u have got any clue regarding it then please reply

**Comment by sasensi** [comment]
@160303105370, what browser are you using ?
Does this [fiddle](https://jsfiddle.net/w3f7tqv2/) work for you ?

**Comment by Spoonhead88** [comment]
i had the exact same problem. I just copy and pasted that fiddle and it worked. now i have no idea why...

**Comment by kn1ghtfall** [comment]
Check if you commented your code with  , yes this is the html way but when you write in a <script> tag use /* */ to comment. This worked for me

**Comment by jumpjack** [comment]
I have a similar issue: there is a syntax error somewhere in my  1200 lines script, but papar.js does not provide any clue about where it is; can this be fixed? can paper.js provide any feedback in console about the line which causes trouble?

```
Uncaught SyntaxError: Unexpected token (242:31) (at paper-full.min.js:32:208210)
    at k (paper-full.min.js:32:208210)
    at ve (paper-full.min.js:32:224901)
    at Oe (paper-full.min.js:32:231197)
    at Ae (paper-full.min.js:32:229397)
    at paper-full.min.js:32:228839
    at paper-full.min.js:32:228850
    at Me (paper-full.min.js:32:228980)
    at Me (paper-full.min.js:32:229053)
    at Pe (paper-full.min.js:32:228429)
    at Le (paper-full.min.js:32:231909)
```

**Comment by jumpjack** [comment]
> I close this issue as it seems that there was no problem with `Paper.js`.

I don't understand this reply: the problem with paper.js is that it does not provide feedback about error location.

**Comment by jumpjack** [comment]
Some tests alowed me a better estimating approximate location of the error: I modified  parseTopLevel() function adding a couple of console.log():

      function parseTopLevel(program) {
    	lastStart = lastEnd = tokPos;
    	if (options.locations) lastEndLoc = new line_loc_t;
    	inFunction = strict = null;
    	labels = [];
    	readToken();
    console.log("START",startNode().start)	  
    
    	var node = program || startNode(), first = true;
    	if (!program) node.body = [];
    	while (tokType !== _eof) {
    	  var stmt = parseStatement();
    	  node.body.push(stmt);
    	  if (first && isUseStrict(stmt)) setStrict(true);
    	  first = false;
    console.log("STMT=",stmt);		
    	}
    	return finishNode(node, "Program");
      }

The result is:

    START 1832
    
    STMT= node_t {type: 'ExpressionStatement', start: 4481, end: 4497, range: Array(2), expression: node_t}
    STMT= node_t {type: 'FunctionDeclaration', start: 4500, end: 6910, range: Array(2), id: node_t, …}
    ....
    ....
    STMT= node_t {type: 'ExpressionStatement', start: 6921, end: 6937, range: Array(2), expression: node_t}

    paper-full.js:15781 Uncaught SyntaxError: Unexpected token (238:31)
        at raise (paper-full.js:15781:12)
        at unexpected (paper-full.js:16421:2)
        at parseExprAtom (paper-full.js:16867:4)
        at parseExprSubscripts (paper-full.js:16787:25)
        at parseMaybeUnary (paper-full.js:16773:13)
        at parseExprOps (paper-full.js:16739:21)
        at parseMaybeConditional (paper-full.js:16726:13)
        at parseMaybeAssign (paper-full.js:16712:13)
        at parseMaybeAssign (paper-full.js:16718:17)
        at parseExpression (paper-full.js:16701:13)


Last line before the error message shows the error location: start = 6921, end = 6937

Problem is that... it's not true: the real location is not 6921 but 7984, which is NOT 6921 + 1832; the error position is counted in a variant of my source which I cannot understand: maybe without empty lines, maybe without commented lines,.... but everything I tested did not work.

**So question is: how do I calculate error position starting from that "6921"?** 

How is this number assigned?

Or is there another method to find the line of the error?

In my specific case, the error is caused by this line:

    camData.segments.forEach( (s) => { console.log(s.y, 10 * Math.sin(s.y) - 2)});

Weird thing is that this line works perfectly from console...
