### ISSUE TITLE
boolean path.subtract() fails with overlapping rectangles

### ISSUE THREAD

**Issue by renschler** [paperjs/paper.js#1541]
Background: I am trying to write a function that will dedup paths, and during that process I came across this issue. This is potentially related to #1540 

---
I've reproduced this issue here: [sketch](http://sketch.paperjs.org/#S/pVfRbpswFP0Vi5cSjdJgYJOoOmna66RNbaU9lD4YcBMWx0TY2dpF+fdhA8YOEGjGG77Xx+ce33tIDhZFW2xF1sMG83RtOVZaZOL9NyoB428Ef09+4ZSDO3CIKagexstig3/mGV9HwHP0xa8FKcoIxFZCULqJrZgeYxpTAZXkq/sahuI/4Afia1e8I7oi2JZLRU65HS6dcLlwZNJD/hfbcLl0vOVysbitcdgWEXIRkqchxbTh48oSKyyt1Fs9qsqqcmKrKKtjcGxVKYrICIQeN0ESsq8hjHoe8auqSRQg3s1y/Jq7scN9yQkZgDaT0oJyTLlMUZFr7VF0msKnyYAglGy0DSdcNK30JJ1Ls34985FYbUNxzLgnVO903ie8RCm3G1gHHHLKcMkjwMs9doCI4gi8IMLwUZC/uZEoIzfYRqttlBHEsX14jUBV+lsE/E9hg1DVwwqCXVKs7AYNr7ZVhaxtWbnKhxTtuCfFnmbM5cXuG37hLsoyeZjnyeM8cZqAU1CG1ldy3K6MuC7zo1gVYwk+6A3wXsHEPHcVwQpajUkLpLCntZcYI8rXsSHdYbg86rrCQV3r/cOaNpIKHEWjp6hyMCPjVFOoNL1YiE7TBgJO+drH+RY5jeXPMsmxa9LC0zY5BmIkzDFKOGFOoqhTq4SzvBKOmyUc98pJPn23HKLTt8s+nTZwoV36ul3C3vjDeUPrnxlaf3BoPRgaQ+uPDq0/YYT61PoTPugPzqwvZ9Y0wvdLYVph0FkhHLCAmboGZ3QNZplhMKpr0OqaFJwXW0NaiQW1D0wwIWwwKGzQCfsfWghh+9/UwE3XOclKTN0t2tn2bnH3edd9Z2uzUirg1111Es4097OftMvuWuw+X62VEI0OlaROd5sX5NYSj6X3eZzNf1aX0lZ1rku0HNNJS5ypb1mXlSG2/lKW6K3KeQod+Hw7oOJ4T8k2GO2r+oeL3lY64on5DfLrtZm6WJEGSsz2hDO5r/rbkpQYbXaCIbOip+fjPw==) (see test 4, screenshot below for convenience).

![screen shot 2018-10-04 at 5 00 01 pm](https://user-images.githubusercontent.com/3973468/46505552-06d0d900-c7f7-11e8-993e-4f0049876394.png)

There are two overlapping rectangles. When you subtract the smaller rectangle from the larger one, (with trace set to false), it returns a compound path with a segment that should not have been included because it overlaps with the smaller rectangle.

I've also tested this using the build from #1513 (just in case) and I get the same issue.

**Comment by eXponenta** [comment]
Subtract fails with any shapes, when they fully overlap each other, sometimes.
Test: http://bit.ly/2pGCxqS
Draw from red shape to red shape with full overlapping a blue shape.

**Comment by lehni** [comment]
@eXponenta is this related to the problem above? If it's just another boolean operatino problem, then please create a new issue, don't attache to the one here, that is related to using the `{ trace: false }` option.

**Comment by lostpebble** [comment]
I've come across this issue today it seems.

```ts
  const pathRectangle = new paper.Path.Rectangle(new paper.Rectangle(10, 10, width - 20, height - 20));
  let compoundPath: PathItem = new paper.CompoundPath(originalPath);
  compoundPath = compoundPath.intersect(pathRectangle, { trace: false });
```

Trying anything else works, but passing `trace: false` throws this error:

```
TypeError: path.getPointAt is not a function
    at addPath (C:\dev\_projects\vibescout-web-workspace\node_modules\paper\dist\paper-full.js:10135:27)
    at splitBoolean (C:\dev\_projects\vibescout-web-workspace\node_modules\paper\dist\paper-full.js:10150:3)
    at traceBoolean (C:\dev\_projects\vibescout-web-workspace\node_modules\paper\dist\paper-full.js:10070:11)
    at CompoundPath.intersect (C:\dev\_projects\vibescout-web-workspace\node_modules\paper\dist\paper-full.js:10710:11)
```

**Comment by lostpebble** [comment]
I managed to solve my issue:

```ts
  const pathRectangle = new paper.Path.Rectangle(new paper.Rectangle(10, 10, width - 20, height - 20));
  const compoundPath: CompoundPath = new paper.CompoundPath(originalPath);
  const newCompoundPath: CompoundPath = new paper.CompoundPath();
  for (const subPath of compoundPath.children as PathItem[]) {
    newCompoundPath.addChild(subPath.intersect(pathRectangle, { trace: false }));
  }
```

This issue is that using `CompoundPath` with `intersect` seems to not work at the moment. I had to instead run it on the individual children paths within.

**Comment by SteamWind** [comment]
I experienced the same issue as @lostpebble. You should create a new issue.

**Comment by webholics** [comment]
This issue is still open. Had the same issue today.
