### ISSUE TITLE
Simple require of paper.js fails in jest context

### ISSUE THREAD

**Issue by aalexgabi** [paperjs/paper.js#1805]
I created this repo to reproduce the problem: https://github.com/aalexgabi/paper-jest-require-fail/tree/master

In a jest context running:
```sh
const paper = require('paper');
```
Fails with:
```
% npx jest test.spec.js                                                     
 FAIL  ./test.spec.js
  ● Test suite failed to run

    Canvas [object HTMLCanvasElement] is unable to provide a 2D context.

    > 1 | const paper = require('paper');
        | ^
      2 | 

      at Object.getCanvas (node_modules/paper/dist/paper-full.js:14297:10)
      at Object.getContext (node_modules/paper/dist/paper-full.js:14312:21)
      at new <anonymous> (node_modules/paper/dist/paper-full.js:14511:27)
      at Object.<anonymous> (node_modules/paper/dist/paper-full.js:14325:17)
      at Object.<anonymous> (node_modules/paper/dist/paper-full.js:17383:3)
      at Object.<anonymous> (test.spec.js:1:1)

  console.error
    Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
        at module.exports (/tmp/aa/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
        at HTMLCanvasElementImpl.getContext (/tmp/aa/node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:42:5)
        at HTMLCanvasElement.getContext (/tmp/aa/node_modules/jsdom/lib/jsdom/living/generated/HTMLCanvasElement.js:41:47)
        at Object.getCanvas (/tmp/aa/node_modules/paper/dist/paper-full.js:14295:20)
        at Object.getContext (/tmp/aa/node_modules/paper/dist/paper-full.js:14312:21)
        at new <anonymous> (/tmp/aa/node_modules/paper/dist/paper-full.js:14511:27)
        at Object.<anonymous> (/tmp/aa/node_modules/paper/dist/paper-full.js:14325:17)
        at Object.<anonymous> (/tmp/aa/node_modules/paper/dist/paper-full.js:17383:3)
        at Runtime._execModule (/tmp/aa/node_modules/jest-runtime/build/index.js:1207:24)
        at Runtime._loadModule (/tmp/aa/node_modules/jest-runtime/build/index.js:807:12) undefined

      at VirtualConsole.<anonymous> (node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
      at module.exports (node_modules/jsdom/lib/jsdom/browser/not-implemented.js:12:26)
      at HTMLCanvasElementImpl.getContext (node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:42:5)
      at HTMLCanvasElement.getContext (node_modules/jsdom/lib/jsdom/living/generated/HTMLCanvasElement.js:41:47)
      at Object.getCanvas (node_modules/paper/dist/paper-full.js:14295:20)
      at Object.getContext (node_modules/paper/dist/paper-full.js:14312:21)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.61s
Ran all test suites matching /test.spec.js/i.
```

If I add to `jest.config.js` (see node-env branch of the repo https://github.com/aalexgabi/paper-jest-require-fail/tree/node-env):
```js
module.exports = {
  // The test environment that will be used for testing
  testEnvironment: "node",
};
```
I get a warning:
```
% npx jest test.spec.js
 FAIL  ./test.spec.js
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (node_modules/@jest/core/build/TestScheduler.js:173:18)

  console.warn
    `require.cache` modification is not permitted

      at Object.notPermittedMethod (node_modules/jest-runtime/build/index.js:1512:44)
      at node_modules/stealthy-require/lib/index.js:24:33
      at forEach (node_modules/stealthy-require/lib/index.js:10:9)
      at clearCache (node_modules/stealthy-require/lib/index.js:22:5)
      at module.exports (node_modules/stealthy-require/lib/index.js:32:5)
      at Object.<anonymous> (node_modules/request-promise-native/lib/rp.js:7:15)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.669s
Ran all test suites matching /test.spec.js/i.
```

It seems that for some reason paper.js tries to use a canvas when running in a jest context with jsdom. I want to use `paper.setup([100, 100])` instead and not use any canvas because I use paper.js only for 2d geometry math.

Require should not fail and shouldn't do anything until I call `paper.setup()`.

**Comment by sapics** [comment]
@aalexgabi How about `paper-jsdom` ? It would be nice for headless use.

**Comment by aalexgabi** [comment]
@sapics I use paper.js only for 2d geometry math. I don't want to install jsdom just for calling pure math functions.
