### ISSUE TITLE
Cannot read property '_currentStyle' of null when  new Path is called

### ISSUE THREAD

**Issue by ievgennaida** [paperjs/paper.js#1889]
"paper": "0.12.8",

# Description/Steps to reproduce
call from a browser:

new paper.Path('m -290.73 38.52 s -2 9.599999999999994 34.80000000000001 -0.8000000000000043 l 6.800000000000011 0.8000000000000043 c 2.4000000000000057 0.7999999999999972 14.400000000000006 3.5999999999999943 16.400000000000006 2.3999999999999986 c 0 0 -7.200000000000017 13.600000000000001 -18.80000000000001 12 c 0 0 -13.200000000000017 1.6000000000000014 -12.799999999999983 6.399999999999999 c 0 0 4 7.199999999999996 8.799999999999983 9.600000000000001 c 0 0 2.8000000000000114 2.3999999999999915 2.4000000000000057 5.599999999999994 s -3.1999999999999886 4.799999999999997 -5.199999999999989 5.6000000000000085 s -5.199999999999989 -2.4000000000000057 -6.800000000000011 -2.4000000000000057 s -10 -6.400000000000006 -14.399999999999977 -11.200000000000003 s -12.800000000000011 -16.799999999999997 -12.400000000000034 -19.599999999999994 s 1.1999999999999886 -8.399999999999999 1.1999999999999886 -8.399999999999999 Z');

failed with an error:

Cannot read property '_currentStyle' of null
    at Path._initialize (paper-full.js:3225)
    at new Path (paper-full.js:8347)

line:

		this._style = new Style(project._currentStyle, this, project);

# Expected result
Should not fail.

# Additional information
windows.

**Comment by sapics** [comment]
Thanks for report.
I have checked in [sketch](http://sketch.paperjs.org/#V/prebuilt/S/jVPLTsMwEPyVVS4BCVtev1PEiR9A4gblkKaRitImVRLBAfHvbHhIXTsH7EvszM7O7ng/ir4+tcWmeOzauTkUN0Uz7JfzWz3CuZ4PcAd9+w4P9HlVnkDoSslgwETpNEx0hkq66nJZMFZGdbEQhOI3yho4gk9gCCuwBrS07NIFwgWWM2hAm8A8mFSZAfQZSkvDUNFTTkVbBKmZvgBopGfhVBrGtFrUfwyEzyhSBkswzeuJhnrDVVW/lBaCRPbDQ8yiq0zmT7ROO26z8tGtNdxlJpP3hiuJ1DmbGgPCJaiKyLi66Ba2HCdWhIj80azBiA/VAk7dFvROWMGBOBG5Tcp8E2TdojufF4hJfrM4mk/FRNZn/RIx8/l/qKfy+nbbLxMqp3kcuvZ+OA4jTWu5O9ZNV257muXd2NbdeXjt56nYPL98fgE=) in prebuilt version or 0.12.7 version, it makes no errors.
Could you make reproduction case?

**Comment by ievgennaida** [comment]
@sapics
The constructor was called from angular.
No other setup is made. Just new paper.Path constructor is called.

**Comment by sapics** [comment]
#1490 looks same problem. It might help you.

**Comment by ievgennaida** [comment]
@sapics Might be, but I have tried to use lib without visualization. I would expect that it suppose to work without any other setup made.

**Comment by fehergeri13** [comment]
Same issue here. I need to call `paper.setup(new paper.Size(1000, 1000));` although i just need to calculate intersections.

**Comment by BURROO** [comment]
Has there been a solution or work around for this? Running into the same issue. In my case @fehergeri13 solution didn't fix the error. I am also only calculating intersection without the need for visualisation.

**Comment by sapics** [comment]
We need a reproduction case for fixing bug.

@BURROO 
Yes, it is possible. `paper-jsdom` or `paper-jsdom-canvas` would help you!
https://github.com/paperjs/paper.js#installing-paperjs-using-npm

**Comment by fehergeri13** [comment]
@sapics Here is my demo repo: https://github.com/fehergeri13/paper-problem

**Comment by sapics** [comment]
@fehergeri13 Thanks for reproduction case!
As you noticed, we need to call `paper.setup([1000, 1000]);` as https://github.com/sapics/paper-problem/blob/master/index.test.ts, in this case.

**Comment by fehergeri13** [comment]
> @fehergeri13 Thanks for reproduction case! As you noticed, we need to call `paper.setup([1000, 1000]);` as https://github.com/sapics/paper-problem/blob/master/index.test.ts, in this case.

Exactly, thats what I want to **avoid**. I just want to calculate intersections, without any global initialisation.

> Same issue here. I need to call `paper.setup(new paper.Size(1000, 1000));` although i just need to calculate intersections.

**Comment by sapics** [comment]
Sorry I am not good at English. Thus, I have not understand well what is `without any global initialisation`, I guess that current version would not be possible to avoid `paper.setup`.

I know that some users request the feature to paperjs `without canvas`, because easier to use in many environments and better performance.
Are there any other reasons which you wish to avoid `any global initialisation`?
If there are more reasonable issues, the feature would have more priority.

**Comment by MonkRocker** [comment]
I am also having this issue, but for different reasons.  

So since @sapics  asked why someone wouldn't want to use any global initialization is because:  on a HUGE project - why on earth would I shoot myself in the foot right from the start?  Global vars haven't been considered best practice since nearly the dawn of programming, so it's odd to me that it's the only way Paper works.  I have a HUGE project with multiple pages.  Only ONE of them uses Paper.  Seems like a lot to ask to make it all global just for ONE page.

So I wrote an object to manage my canvas via paper for that ONE page.

Is there a way to specify a project?  When I set up paper, I am grabbing a reference to the project, but no other call to paper seems to use that reference, and there doesn't seem to be a way to tell it to.

So here is my function to setup paper and the canvas, called from a Vue component, which has just created the canvas and sized it correctly:

```
init: function (canvas) {
      console.log(`GCM::init BEGIN: ${canvas.width}x${canvas.height}`);
      this.canvas = canvas;
      this.scope = new paper.PaperScope();
      // setup paper
      paper.install(window);
      this.project = new paper.Project(canvas);
      this.project.activate();
      this.scope.setup(canvas);
      this.drawAreas = new paper.Group();
      console.log(`GCM::init END`);
      return this.view;
    }
```

That runs fine, and I get my canvas displaying.  But then a few lines later, I am trying to load a background image onto the canvas using a Raster:

```
loadBackground: function (bgImage) {
      LAWG(`GameCanvasManager::loadBackground:BEGIN`, bgImage, this.scope.project);
      const source = require(`../../data/maps/bg-images/${bgImage}`);
      LAWG(source);
      // god Paper is SO persnickety
      // paper.setup([this.canvas.height, this.canvas.width]);
      this.scope.project.addChild(new Raster({
        source,
        position: this.scope.view.center,
      }));
      LAWG(`GameCanvasManager::loadBackground:END`);
    }
```

and I get:

```
Uncaught (in promise) TypeError: project is null
    _initialize paper-core.js:3222
    Raster paper-core.js:5369
    loadBackground GameCanvasManager.js:54
```

I know project is there, because logging out this.project on that object shows a project, but paper doesn't see it.

Is there some way to tell paper "use this instance of project" ?

**Comment by fehergeri13** [comment]
For anyone who want to initialise paperjs without any canvas and save performance, this is my current solution:
It works both on nodejs and browser


```
import paper from "paper";
paper.setup(new paper.Size(1, 1)); // creates a virtual canvas
paper.view.autoUpdate = false; // disables drawing any shape automatically
```

**Comment by Typogram** [comment]
I spent a day debugging this error and wanted to share the solution in case it helps others.


### Context
This error occurred intermittently in my app:
- It would appear during stress testing
- Specifically when clicking to re-render fonts which creates new `paper.CompoundPath` instances
- Behavior was inconsistent: would work fine, then fail on next click, then work again immediately after

### Error
The error occurs because Paper.js needs an active scope to properly initialize style properties. When multiple operations are happening quickly (like during stress testing), the scope can become incorrect, leading to the `_currentStyle` being null.

```
chunk-BXNP5SZD.js?v=87eb6566:8010 Uncaught (in promise) TypeError: Cannot read properties of null (reading '_currentStyle') 
at CompoundPath2._initialize (chunk-BXNP5SZD.js?v=87eb6566:8010:45) 
at new CompoundPath2 (chunk-BXNP5SZD.js?v=87eb6566:13662:23) 
at Letter.render (letter.ts:803:20) 
at async Text.render (text.ts:907:9) 
at async handlePropertyFontFamilyChange (PropertyAny.svelte:47:27)
```

### Solution
Add this line before creating any new CompoundPath:
```javascript
letterGroup.project._scope.activate();
```
Note: `letterGroup.project._scope` is just my app's way of finding the paperScope that should be activate.

After adding this line, then it is safe to create new CompoundPath
```
const path = new paper.CompoundPath(...);
```

**Comment by cprcrack** [comment]
It would be great being able to use Paper.js without any global initialisation. I just want to use paper.Path intersection functions and it feels strange having to `paper.setup([1, 1]); paper.view.autoUpdate = false;` for that.
