### ISSUE TITLE
latest jsdom 4.0 only works on io.js

### ISSUE THREAD

**Issue by Knape** [paperjs/paper.js#641]
When installing paperjs as a npm module, it installs version 0.4 of jsdom which only works on io.js. 

When trying to require paperjs inside node it now returns the error:
this._globalProxy = vm.runInContext("this", this);

It would be good to only allow version ~3.0 of jsdom. 

Running:
Nodejs v0.10.35
ubuntu v14.04 LTS 64bit

**Comment by zowers** [comment]
same issue here
```
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/app/node_modules/paper/node_modules/jsdom/lib/jsdom/level1/core.js:8:20)

```

**Comment by zowers** [comment]
also same problem with canvas:
```
"canvas": ">= 0.7.0",
```

**Comment by lehni** [comment]
This was fixed in #644. But what's the issue with `"canvas": ">= 0.7.0"`?

**Comment by zowers** [comment]
the issues will arise when some future version of canvas will be incompatible with paper. the same way as jsdom now

**Comment by lehni** [comment]
You're right. Changed now!
