### ISSUE TITLE
Loading multiple Rasters in Node.JS throws an error

### ISSUE THREAD

**Issue by rbvea** [paperjs/paper.js#645]
When loading more than one remote Rasters in node, it throws an error.  This code:

```
  var canvas = new paper.Canvas(800,600);
  paper.setup(canvas);
  var photo = new paper.Raster('https://upload.wikimedia.org/wikipedia/commons/9/9a/Pentonville_Prison_ILN_1842.jpg');
  var photo2 = new paper.Raster('https://upload.wikimedia.org/wikipedia/commons/f/f5/Katsunuma.jpg');
```

throws this error:

```
   Uncaught Error: Image given has not completed loading
    at Raster.Item.extend._draw (/Users/rbvea/paperjs/node_modules/paper/dist/paper-node.js:4888:8)
    at Raster.Base.extend.draw (/Users/rbvea/paperjs/node_modules/paper/dist/paper-node.js:4020:8)
    at Layer.Item.extend._draw (/Users/rbvea/paperjs/node_modules/paper/dist/paper-node.js:4163:11)
    at Layer.Base.extend.draw (/Users/rbvea/paperjs/node_modules/paper/dist/paper-node.js:4020:8)
    at Project.PaperScopeItem.extend.draw (/Users/rbvea/paperjs/node_modules/paper/dist/paper-node.js:2544:14)
    at CanvasView.View.extend.update (/Users/rbvea/paperjs/node_modules/paper/dist/paper-node.js:10517:11)
    at loaded (/Users/rbvea/paperjs/node_modules/paper/dist/paper-node.js:4705:10)
    at Request._callback (/Users/rbvea/paperjs/node_modules/paper/dist/paper-node.js:4722:6)
    at Request.self.callback (/Users/rbvea/paperjs/node_modules/paper/node_modules/request/request.js:129:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/rbvea/paperjs/node_modules/paper/node_modules/request/request.js:873:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/rbvea/paperjs/node_modules/paper/node_modules/request/request.js:824:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
```

this is running locally on `OSX Yosemite` and `node = v0.10.36`.

**Comment by lehni** [comment]
You're right. When the first image is loaded, a redraw is caused, and the 2nd image that is not ready yet is drawn to the canvas, causing this exception. Should be fairly trivial to fix.
