### ISSUE TITLE
Paper on node v0.12 Error: Module did not self-register.

### ISSUE THREAD

**Issue by JohnMcLear** [paperjs/paper.js#649]
Looks like it's upstream (contextify) error bubbling down.

https://github.com/JohnMcLear/draw/issues/185#issuecomment-76736137

```
~$ draw/bin/run.sh                                                                                           
Ensure that all dependencies are up to date...
start...
DirtyDB is used. This is fine for testing but not recommended for production.
/home/user/draw/node_modules/paper/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/home/user/draw/node_modules/paper/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/user/draw/node_modules/paper/node_modules/jsdom/node_modules/contextify/lib/contextify.js:1:96)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

**Comment by lehni** [comment]
Did you perform `npm install` after the update?

**Comment by lehni** [comment]
I just tried out installing a fresh paper on Node at my end and executing one of the examples, works without hick-ups. I'm not sure what's causing this at your end, but perhaps try reinstalling all dependencies.

**Comment by JohnMcLear** [comment]
Yea I can't replicate, will close.
